import type { NextPage } from "next";
import Head from "next/head";
import styles from "../../styles/home.module.css";
import BackToHome from "../../components/BackToHome";
import SummaryTable from "../../components/SummaryTable";
import Footer from "../../components/Footer";
import getStaff from "../../lib/data/getStaff";
import Heading, { Headings } from "../../components/Heading";
import { Staff } from "../../types/Staff";
import DataFrame from "../../lib/DataFrame/DataFrame";
import { MdOutlineArrowRightAlt } from "react-icons/md";
import Link from "next/link";

type Props = React.PropsWithChildren<{
  staff: Staff[];
}>;

const Staff: NextPage<Props> = ({ staff }) => {
  const staffDf = new DataFrame(staff);
  return (
    <>
      <Head>
        <title>ITC's staff</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Heading Tag={Headings.H1}>Staff</Heading>
        <p className={styles.description}>Insights into ITC's staff members.</p>
        <p>
          <BackToHome />
        </p>

        <div className={styles.grid}>
          <Link href="/staff/origin">
            <a className={styles.card}>
              <h2>
                Origin <MdOutlineArrowRightAlt />
              </h2>
            </a>
          </Link>
        </div>

        <SummaryTable data={staffDf} />
      </main>

      <Footer />
    </>
  );
};

export async function getStaticProps() {
  const staff = await getStaff();
  return {
    props: {
      staff,
    },
  };
}

export default Staff;
