import type { NextPage } from "next";
import Head from "next/head";
import styles from "../../styles/home.module.css";
import BackToHome from "../../components/backToHome";
import SummaryTable from "../../components/summaryTable";
import Footer from "../../components/footer";
import getStaff from "../../lib/getStaff";
import Heading, { Headings } from "../../components/heading";
import getTestData from "../../lib/getTestData";
import { Staff } from "../../types/Staff";

type Props = React.PropsWithChildren<{
  staff: Staff[];
}>;

const Staff: NextPage<Props> = ({ staff }) => {
  return (
    <>
      <Head>
        <title>ITC's staff</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Heading Tag={Headings.H1}>Staff</Heading>
        <p className={styles.description}>Insights into ITC's staff members.</p>
        <p>
          <BackToHome />
        </p>
        {/* <Snapshot
          column={staff.map((row) => row.dateOfBirth)}
          type={ColumnType.Date}
          columnName="Date of Birth"
          detailed={true}
        /> */}
        <SummaryTable table={staff} />
      </main>

      <Footer />
    </>
  );
};

export async function getStaticProps() {
  const staff = await getStaff();
  const test = await getTestData();
  return {
    props: {
      staff,
      test,
    },
  };
}

export default Staff;
