import type { NextPage } from "next";
import Head from "next/head";
import styles from "../../styles/home.module.css";
import SummaryTable from "../../components/SummaryTable";
import Footer from "../../components/Footer";
import getStaff from "../../lib/data/getStaff";
import Heading, { Headings } from "../../components/Heading";
import { Staff } from "../../types/Staff";
import DataFrame from "../../lib/DataFrame/DataFrame";
import LinkFramed from "../../components/LinkFramed";

type Props = React.PropsWithChildren<{
  staff: Staff[];
}>;

const StaffPage: NextPage<Props> = ({ staff }) => {
  const staffDf = new DataFrame(staff);
  return (
    <>
      <Head>
        <title>ITC's staff</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Heading Tag={Headings.H1}>Staff</Heading>
        <p className={styles.description}>Insights into ITC's staff members.</p>

        <div className={styles.grid}>
          <LinkFramed href="/staff/origin">Origin</LinkFramed>
        </div>

        <SummaryTable data={staffDf} />
      </main>

      <Footer />
    </>
  );
};

export async function getStaticProps() {
  const staff = await getStaff();
  return {
    props: {
      staff,
    },
  };
}

export default StaffPage;
