import * as d3 from "d3";
import { geoBertin1953 } from "d3-geo-projection";
import type { Feature, FeatureCollection, MultiPolygon, Point } from "geojson";
import { nanoid } from "nanoid";
import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import * as topojson from "topojson-client";
import type { Topology } from "topojson-specification";
import Footer from "../../components/footer";
import Heading, { Headings } from "../../components/heading";
import BaseLayer from "../../components/map/BaseLayer";
import PointSymbol from "../../components/map/PointSymbol";
import ProportionalSymbolLegend from "../../components/map/ProportionalSymbolLegend";
import getMapHeight from "../../lib/cartographic/getMapHeight";
import getCountries from "../../lib/data/getCountries";
import getStaff from "../../lib/data/getStaff";
import styles from "../../styles/home.module.css";
import type { Staff } from "../../types/Staff";

type Props = {
  staff: Staff[];
  world: Topology;
};

const StaffOrigin: NextPage<Props> = ({ staff, world }) => {
  const worldFeatureCollection = topojson.feature(
    world,
    world.objects.countries
  );

  const count = d3.group(staff, (d) => d.nationality);
  const dimension = {
    width: 1280,
    height: 0,
  };

  const projection = geoBertin1953();
  dimension.height = getMapHeight(dimension.width, projection);

  const points: FeatureCollection<Point> = {
    type: "FeatureCollection",
    features: worldFeatureCollection.features
      .map((feature: Feature<MultiPolygon>) => {
        const staffCount = count.get(feature.properties?.iso3code)?.length;
        const pointFeature: Feature<Point> = {
          type: "Feature",
          properties: {
            staffCount,
            ...feature.properties,
          },
          geometry: {
            type: "Point",
            coordinates: [
              d3.geoCentroid(feature)[0],
              d3.geoCentroid(feature)[1],
            ],
          },
        };
        return pointFeature;
      })
      .filter((feature: Feature) => feature.properties?.staffCount)
      .sort((a: Feature, b: Feature) =>
        d3.descending(a.properties?.staffCount, b.properties?.staffCount)
      ),
  };

  const staffCount = points.features.map(
    (point) => point.properties?.staffCount
  );
  const min = d3.min(staffCount);
  const max = d3.max(staffCount);

  const scale = d3
    .scaleSqrt()
    .domain([min, max])
    .range([1, dimension.width / 15]);

  return (
    <>
      <Head>
        <title>ITC's staff origin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Heading Tag={Headings.H1}>ITC's staff origin</Heading>
        <svg width={dimension.width} height={dimension.height}>
          <BaseLayer data={world} projection={projection} />
          <g id="symbols">
            {points.features.map((point) => (
              <PointSymbol
                key={nanoid()}
                xy={projection(point.geometry.coordinates)}
                radius={scale(point.properties?.staffCount)}
              />
            ))}
          </g>
          <ProportionalSymbolLegend
            data={points.features.map(
              (feature) => feature.properties?.staffCount
            )}
            scaleRadius={scale}
            title={"Staff members per Country"}
            unitLabel={"Staff member"}
          />
        </svg>
      </main>
      <Footer />
    </>
  );
};

export const getStaticProps: Awaited<GetStaticProps<Props>> = async () => {
  const staff = await getStaff();
  const world = await getCountries();
  return {
    props: {
      staff,
      world,
    },
  };
};

export default StaffOrigin;
