import type { NextPage } from "next";
import Head from "next/head";
import styles from "../../styles/home.module.css";
import SummaryTable from "../../components/SummaryTable";
import Footer from "../../components/Footer";
import Heading, { Headings } from "../../components/Heading";
import * as aq from "arquero";
import useSWR from "swr";

const Btors: NextPage = () => {
  const { data, error, isLoading } = useSWR("/api/data/btor/");

  return (
    <>
      <Head>
        <title>ITC&apos;s world</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Heading Tag={Headings.H1}>Btors</Heading>

        <p className={styles.description}>
          Insights into ITC&apos;s travels around the globe through the
          &quot;Back to Office&quot; Reports.
        </p>

        {error && <div>failed to load</div>}
        {isLoading && <div>Loading …</div>}
        {!isLoading && !error && <SummaryTable data={aq.from(data)} />}
      </main>

      <Footer />
    </>
  );
};

export default Btors;
