import type { NextPage } from "next";
import Head from "next/head";
import Footer from "../../components/Footer";
import { Container, Grid, Heading, Text } from "theme-ui";
import CardLink from "../../components/CardLink";

const Page: NextPage = () => (
  <>
    <Head>
      <title>ITC&apos;s world</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Container>
      <main>
        <Heading as="h1">Btors</Heading>

        <Text variant="teaser">
          Insights into ITC&apos;s travels around the globe through the
          &quot;Back to Office&quot; reports.
        </Text>

        <Grid variant="navigation">
          <CardLink href={`introduction/travels-by-department`}>
            <Heading as="h2">By department</Heading>
          </CardLink>
        </Grid>
      </main>
    </Container>

    <Footer />
  </>
);

export default Page;
