import type { NextPage } from "next";
import Head from "next/head";
import styles from "../../styles/home.module.css";
import { MdOutlineArrowRightAlt } from "react-icons/md";
import Link from "next/link";
import BackToHome from "../../components/BackToHome";
import SummaryTable from "../../components/SummaryTable";
import { Project } from "../../types/Project";
import getProjects from "../../lib/data/getProjects";
import Footer from "../../components/Footer";
import DataFrame from "../../lib/DataFrame/DataFrame";
import Heading, { Headings } from "../../components/Heading";

type Props = React.PropsWithChildren<{
  projects: Project[];
}>;

const Travels: NextPage<Props> = ({ projects }) => {
  const projectsDf = new DataFrame(projects);
  return (
    <>
      <Head>
        <title>ITC's projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Heading Tag={Headings.H1}>Projects</Heading>

        <p className={styles.description}>
          Insights into ITC's projects around the globe.
        </p>

        <div className={styles.grid}>
          <Link href="/projects/timeline">
            <a className={styles.card}>
              <h2>
                Timeline <MdOutlineArrowRightAlt />
              </h2>
            </a>
          </Link>

          <Link href="/projects/projectcountries">
            <a className={styles.card}>
              <h2>
                by Country <MdOutlineArrowRightAlt />
              </h2>
            </a>
          </Link>
          <Link href="/projects/projectsafrica">
            <a className={styles.card}>
              <h2>
                Sub-Saharan Africa <MdOutlineArrowRightAlt />
              </h2>
            </a>
          </Link>
          <Link href="/projects/naivasha">
            <a className={styles.card}>
              <h2>
                Naivasha Region <MdOutlineArrowRightAlt />
              </h2>
            </a>
          </Link>
          <Link href="/projects/indonesia">
            <a className={styles.card}>
              <h2>
                Indonesia <MdOutlineArrowRightAlt />
              </h2>
            </a>
          </Link>
        </div>
        <p>
          <BackToHome />
        </p>

        <SummaryTable data={projectsDf} />
      </main>

      <Footer />
    </>
  );
};

export async function getStaticProps() {
  const projects = await getProjects();
  return {
    props: {
      projects,
    },
  };
}

export default Travels;
