import type { NextPage } from "next";
import Head from "next/head";
import styles from "../../styles/Home.module.css";
import { MdOutlineArrowRightAlt } from "react-icons/md";
import Link from "next/link";

const Travels: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>ITC's projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Projects</h1>

        <p className={styles.description}>
          Insights into ITC's projects around the globe.
        </p>

        <div className={styles.grid}>
          <Link href="/projects/overview">
            <a className={styles.card}>
              <h2>
                Overview <MdOutlineArrowRightAlt />
              </h2>
            </a>
          </Link>

          <Link href="/projects/timeline">
            <a className={styles.card}>
              <h2>
                Timeline <MdOutlineArrowRightAlt />
              </h2>
            </a>
          </Link>

          <Link href="/projects/projectcountries">
            <a className={styles.card}>
              <h2>
                by Country <MdOutlineArrowRightAlt />
              </h2>
            </a>
          </Link>
        </div>
        <p>
          <Link href="/">
            <a>Back to home</a>
          </Link>
        </p>
      </main>

      <footer className={styles.footer}>March 2022</footer>
    </div>
  );
};

export default Travels;
