import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Heading, { Headings } from "../../components/heading";
import styles from "../../styles/home.module.css";

import { Suspense } from "react";
import { Canvas } from "@react-three/fiber";
import { Environment, OrbitControls } from "@react-three/drei";

import NaivashaRegion from "../../components/models/NaivashaRegion";
import Cubes from "../../components/models/TestCubes";
import LocatorMap from "../../components/map/LocatorMap";
import getCountries from "../../lib/data/getCountries";

type Props = {
  world: Topology;
  model: string;
};

const Naivasha: NextPage<Props> = ({ world, model }) => {
  return (
    <>
      <Head>
        <title>Naivasha Region</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Heading Tag={Headings.H1}>Naivasha Region</Heading>
        <LocatorMap data={world} highlight={["AUS", "DEU"]} />
        <div style={{ width: "100%", height: "500px" }}>
          <Canvas shadows>
            <Suspense fallback={null}>
              {/* <ambientLight castShadow args={[undefined, 1]} /> */}
              <directionalLight
                castShadow
                position={[10, 10, 0]}
                args={["white", 1]}
              />
              <mesh castShadow position={[0, 10, 0]}>
                <boxGeometry args={[2, 2, 2]} />
                <meshStandardMaterial color={"orange"} />
              </mesh>
              <Cubes position={[0, 20, 0]} />
              <mesh receiveShadow position={[0, -1, 0]}>
                <boxGeometry args={[150, 1, 150]} />
                <meshBasicMaterial color={"white"} />
              </mesh>
              <NaivashaRegion castShadow position={[0, 3, 0]} />
              <OrbitControls />
            </Suspense>
          </Canvas>
        </div>
      </main>
    </>
  );
};

export const getStaticProps: GetStaticProps<Props> = async () => {
  const world = await getCountries();
  return {
    props: {
      model: "",
      world,
    },
  };
};

export default Naivasha;
