import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import styles from "../../styles/home.module.css";
import { geoBertin1953 } from "d3-geo-projection";
import * as d3 from "d3";
import * as topojson from "topojson-client";
import { Project } from "../../types/Project";
import getCountries from "../../lib/data/getCountries";
import getProjects from "../../lib/data/getProjects";
import BaseLayer from "../../components/map/BaseLayer";
import Heading, { Headings } from "../../components/Heading";
import { FeatureCollection, Feature, Point, MultiPolygon } from "geojson";
import PointSymbol from "../../components/map/PointSymbol";
import ProportionalSymbolLegend from "../../components/map/ProportionalSymbolLegend";
import getMapHeight from "../../lib/cartographic/getMapHeight";
import { AreaCode } from "../../types/UnsdCodes";
import getUnsdCountries from "../../lib/data/getUnsdCountries";
import { nanoid } from "nanoid";
import PatternLines from "../../components/defs/patterns/PatternLines";
import themes from "../../lib/styles/themes";
import ChoroplethSymbol from "../../components/map/ChoroplethSymbol";

type Props = {
  projects: Project[];
  world: Awaited<ReturnType<typeof getCountries>>;
  areaCodes: AreaCode[];
};

const ProjectCountries: NextPage<Props> = ({ projects, world, areaCodes }) => {
  const dimension = {
    width: 1280,
    height: 0,
  };
  const theme = themes.eth;
  const projection = geoBertin1953();
  dimension.height = getMapHeight(dimension.width, projection);

  const count = d3
    .rollups(
      projects.reduce((acc: string[], proj) => {
        acc.push(...proj.countries); // or proj.allCountries
        return acc;
      }, []),
      (v) => v.length,
      (d) => d
    )
    .sort((a, b) => d3.descending(a[1], b[1]));
  const projectsCountry = new Map(count);

  const minRadius = 1;
  const maxRadius = 30;

  const projectCount = Array.from(projectsCountry.values());
  const minRange = d3.min(projectCount) ?? 0; // TODO: meaningful fallback values
  const maxRange = d3.max(projectCount) ?? 10;

  const scale = d3
    .scaleSqrt()
    .domain([minRange, maxRange])
    .range([minRadius, maxRadius]);

  const points: FeatureCollection<Point> = {
    type: "FeatureCollection",
    features: topojson
      .feature(world, world.objects.countries)
      .features.map((feature: Feature<MultiPolygon>) => {
        const value = projectsCountry.get(feature.properties?.iso3code);
        return {
          type: "Feature",
          properties: {
            projectCount: value,
            ...feature.properties,
          },
          geometry: {
            coordinates: [
              d3.geoCentroid(feature)[0],
              d3.geoCentroid(feature)[1],
            ],
          },
        };
      })
      .filter((feature: Feature) => feature.properties?.projectCount),
  };

  const polygons: FeatureCollection<MultiPolygon> = {
    type: "FeatureCollection",
    features: topojson
      .feature(world, world.objects.countries)
      .features.filter((feature: Feature<MultiPolygon>) => {
        const matchedCountry = areaCodes.find(
          (area) => area["ISO-alpha3 Code"] === feature.properties?.iso3code
        );
        const highlight = matchedCountry?.["Least Developed Countries (LDC)"];
        return highlight;
      }),
  };

  return (
    <>
      <Head>
        <title>ITC's Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Heading Tag={Headings.H1}>ITC's global project activity</Heading>
        <svg width={dimension.width} height={dimension.height}>
          <defs>
            <PatternLines
              style={theme.choropleth?.pattern}
              angle={20}
            ></PatternLines>
          </defs>
          <BaseLayer data={world} projection={projection} theme={theme} />
          <g className="choroplethLayer">
            {polygons.features.map((feature) => (
              <ChoroplethSymbol
                key={nanoid()}
                projection={projection}
                feature={feature}
                theme={theme}
              />
            ))}
          </g>
          <g className="symbolLayer">
            {points.features.map((feature) => (
              <PointSymbol
                key={nanoid()}
                xy={projection(feature.geometry.coordinates)}
                radius={scale(feature.properties?.projectCount)}
                style={theme.symbol}
              />
            ))}
          </g>
          <ProportionalSymbolLegend
            key={nanoid()}
            data={points.features.map(
              (feature) => feature.properties?.projectCount ?? 0
            )}
            scaleRadius={scale}
            title={"Projects per Country"}
            unitLabel={"project"}
            style={theme.symbol}
          />
        </svg>
      </main>
    </>
  );
};

export const getStaticProps: GetStaticProps<Props> = async () => {
  const projects = await getProjects();

  const projectSelection = projects.filter(
    (
      row
    ): row is Omit<Project, "dateStart" | "dateEnd" | "projectID"> & {
      dateStart: string;
      dateEnd: string;
      projectID: string;
    } => typeof row.dateStart === "string" && typeof row.dateEnd === "string"
  );

  projectSelection.sort((a, b) =>
    d3.ascending(new Date(a.dateStart), new Date(b.dateStart))
  );

  const world = await getCountries();
  const areaCodes = await getUnsdCountries();

  return {
    props: {
      projects: projectSelection,
      world,
      areaCodes,
    },
  };
};

export default ProjectCountries;
