import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import styles from "../../styles/home.module.css";
import BackToHome from "../../components/BackToHome";
import getTravels from "../../lib/data/getTravels";
import SummaryTable from "../../components/SummaryTable";
import Footer from "../../components/Footer";
import DataFrame from "../../lib/DataFrame/DataFrame";
import Heading, { Headings } from "../../components/Heading";
import type { Travel } from "../../types/Travels";

type Props = {
  travels: Travel[];
};

const Travels: NextPage<Props> = ({ travels }) => {
  const travelsDf = new DataFrame(travels);
  return (
    <>
      <Head>
        <title>ITC's world</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Heading Tag={Headings.H1}>Travels</Heading>

        <p className={styles.description}>
          Insights into ITC's travels around the globe.
        </p>

        <SummaryTable data={travelsDf} />
        <p>
          <BackToHome />
        </p>
      </main>

      <Footer />
    </>
  );
};

export const getStaticProps: GetStaticProps<Props> = async () => {
  const travels = await getTravels();
  return {
    props: {
      travels,
    },
  };
};

export default Travels;
