import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import getTravels from "../../lib/data/getTravels";
import SummaryTable from "../../components/SummaryTable";
import Footer from "../../components/Footer";
import { Container, Heading, Text } from "theme-ui";
import type { Travel } from "../../types/Travels";
import * as aq from "arquero";

type Props = {
  travels: Travel[];
};

const Travels: NextPage<Props> = ({ travels }) => {
  return (
    <>
      <Head>
        <title>ITC&apos;s world</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <main>
          <Heading as="h1">Travels</Heading>

          <Text variant="teaser">
            Insights into ITC&apos;s travels around the globe.
          </Text>

          <SummaryTable data={aq.from(travels)} />
        </main>
      </Container>

      <Footer />
    </>
  );
};

export const getStaticProps: GetStaticProps<Props> = async () => {
  const travels = await getTravels();
  return {
    props: {
      travels,
    },
  };
};

export default Travels;
