export const countryMapNE: { [key: string]: string } = {
  "Amerikaans burger": "United States of America",
  "Amerikaans Burger": "United States of America",
  "Amerikaans onderdaan": "United States of America",
  "Bondsrepubliek Duitsland, burger van": "Germanny",
  "Brits burger": "United Kingdom",
  "Brits Burger": "United Kingdom",
  "Burger Bangladesh": "Bangladesh",
  "Burger Bondsrepubliek Duitsland": "Germany",
  "Burger India": "India",
  "Burger Nigeria": "Nigeria",
  "Burger Rusland": "Russia",
  "Burger van de Bondsrepubliek Duitsland": "Germany",
  "Costa Ricaanse": "Costa Rica",
  "Georgië, burger van": "Georgia",
  "India, burger van": "India",
  "Kroatië, burger van": "Croatia",
  "Nieuw-Zeelandse": "New Zealand",
  "Niger, burger van": "Niger",
  "Nigeria, burger van": "Nigeria",
  "Oekraine, burger van": "Ukraine",
  "Rusland, burger van": "Russia",
  "Saoedi-Arabische": "South Arabia",
  "Slovenië, burger van": "Slovenia",
  "Sri Lankaanse": "Sri Lanka",
  "Ver. Arabische Emiraten, burger van": "United Arab Emirates",
  "Zuid-Afrikaanse": "South Africa",
  Albanese: "Albania",
  Angolese: "Angola",
  Argentijnse: "Argentina",
  Australische: "Australia",
  Belgische: "Belgium",
  Bengalese: "Bengale",
  Boliviaanse: "Bolivia",
  Botswaanse: "Botswana",
  Braziliaanse: "Brazilia",
  Bulgaarse: "Bulgaria",
  Canadese: "Canada",
  Chileense: "Chile",
  Chinese: "China",
  Colombiaanse: "Columbia",
  Cubaanse: "Cuba",
  Deense: "Denmark",
  Ecuadoraanse: "Ecudaor",
  Egyptische: "Egypt",
  Estnische: "Estonia",
  Ethiopische: "Ethiopia",
  Etiopische: "Ethiopia",
  Filipijnse: "Philippines",
  Finse: "Finland",
  Franse: "France",
  Georgische: "Georgia",
  Ghanese: "Ghana",
  Griekse: "Greece",
  Guatemalaanse: "Guatemala",
  Guatemalteekse: "Guatemala",
  Haïtiaanse: "Haiti",
  Hongaarse: "Hungary",
  Indiase: "India",
  Indonesische: "Indonesia",
  Iraakse: "Iraque",
  Iraanse: "Iran",
  Italiaanse: "Italy",
  Japanse: "Japan",
  Jemenitische: "Yemen",
  Jordaanse: "Jordan",
  Kameroense: "Cameroon",
  Kenyaanse: "Kenya",
  Kirgizische: "Kyrgyzstan",
  Letse: "Latvia",
  Macedonische: "Macedonai",
  Malawische: "Malawi",
  Maleisische: "Malaysia",
  Malinese: "Mali",
  Marokkaanse: "Marocco",
  Mexicaanse: "Mexico",
  Mozambikaanse: "Mozambique",
  Nederlandse: "Netherlands",
  Nepalese: "Nepal",
  Nieuwzeelandse: "New Zealand",
  Nigeriaanse: "Nigeria",
  Oegandese: "Uganda",
  Oostenrijkse: "Austria",
  Pakistaanse: "Pakistan",
  Poolse: "Poland",
  Portugese: "Portugal",
  Roemeense: "Rumania",
  Russische: "Russia",
  Rwandese: "Rwanda",
  Servische: "Serbia",
  Slowaakse: "Slovakia",
  Spaanse: "Spain",
  Srilankaanse: "Sri Lanka",
  Syrische: "Syria",
  Taiwanese: "Taiwan",
  Tanzaniaanse: "Thanzania",
  Thaise: "Thailand",
  Tsjechische: "Czeck Republic",
  Tunesische: "Tunisia",
  Turkse: "Turkey",
  Ugandese: "Uganda",
  Vietnamese: "Viet Nam",
  Zambiaanse: "Zambia",
  Zimbabwaanse: "Zimbabwe",
  Zuidafrikaanse: "South Africa",
  Zuidkoreaanse: "South Korea",
};
