export type Applicant = {
  description: string;
  specialization: string;
  gender: string;
  nationality: string;
  countryOrigin: string;
  city: string;
  level: string;
  prog: string;
  dept: string;
  progDept: string;
  specialAwardMention: string;
  finalResult: string;
  sponsorCategory: string;
  sponsor: string;
  courseNo: string;
  diploma: string;
  dateOfBirth: string;
  dateStart: string;
  dateEnd: string;
  certificateDate: string;
  yearCertExamDipl: string;
  finalScore: string;
  applicantStatus: string;
  thesisTitle: string;
  itcCode: string;
};
