/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    ["220413-lake-naivasha-102113"]: THREE.Mesh;
  };
  materials: {
    ["Material.004"]: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null);
  // @ts-ignore
  const { nodes, materials } = useGLTF(
    "/models/lake-naivasha-green.glb"
  ) as GLTFResult; //TODO: fix typing
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["220413-lake-naivasha-102113"].geometry}
        material={materials["Material.004"]}
        scale={0.001}
      />
    </group>
  );
}

useGLTF.preload("/models/lake-naivasha-green.glb");
