import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Footer from "../../components/Footer";
import Heading, { Headings } from "../../components/Heading";
import SummaryTable from "../../components/SummaryTable";
import DataFrame from "../../lib/DataFrame/DataFrame";
import getAlumni from "../../lib/data/getAlumni";
import styles from "../../styles/home.module.css";
import { Alumni } from "../../types/Alumni";
import React from "react";

import { AgGridReact } from "ag-grid-react"; // the AG Grid React Component
import "ag-grid-community/styles/ag-grid.css"; // Core grid CSS, always needed
import "ag-grid-community/styles/ag-theme-material.css"; // Optional theme CSS
import { ColDef } from "ag-grid-community";

type Props = {
  alumni: Alumni[];
};

const AlumniOverview: NextPage<Props> = ({ alumni }) => {
  const AlumniDf = new DataFrame(alumni);

  const columnDefs: ColDef[] = [
    { field: "contactNo" },
    {
      field: "examYear2",
      headerName: "Exam Year",
      filter: "agDateColumnFilter",
    },
    { field: "city" },
    { field: "populatedPlaceNe" },
    { field: "country" },
    { field: "countryISO3" },
    { field: "courseCode" },
    { field: "level" },
  ];
  const defaultColDef = {
    filter: true,
    sortable: true,
  };

  return (
    <>
      <Head>
        <title>ITC's Alumni</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Heading Tag={Headings.H1}>ITC's Alumni</Heading>

        <p className={styles.description}>Insights into ITC's Alumni.</p>
        <SummaryTable data={AlumniDf} />

        <h2>Data Table</h2>
        <div className="ag-theme-material" style={{ width: 1280, height: 500 }}>
          <AgGridReact
            rowData={alumni}
            columnDefs={columnDefs}
            defaultColDef={defaultColDef}
            pagination={true}
          />
        </div>
      </main>

      <Footer />
    </>
  );
};

export const getStaticProps: GetStaticProps<Props> = async () => {
  const alumni = await getAlumni();
  return {
    props: {
      alumni,
    },
  };
};

export default AlumniOverview;
