import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import BackToHome from "../../components/BackToHome";
import Footer from "../../components/Footer";
import Heading, { Headings } from "../../components/Heading";
import SummaryTable from "../../components/SummaryTable";
import DataFrame from "../../lib/DataFrame/DataFrame";
import getAlumni from "../../lib/data/getAlumni";
import styles from "../../styles/home.module.css";
import { Alumni } from "../../types/Alumni";

type Props = {
  Alumni: Alumni[];
};

const AlumniOverview: NextPage<Props> = ({ Alumni }) => {
  const AlumniDf = new DataFrame(Alumni);
  return (
    <>
      <Head>
        <title>ITC's Alumni</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Heading Tag={Headings.H1}>ITC's Alumni</Heading>

        <p className={styles.description}>Insights into ITC's Alumni.</p>

        <p>
          <BackToHome />
        </p>
        <SummaryTable data={AlumniDf} />
      </main>

      <Footer />
    </>
  );
};

export const getStaticProps: GetStaticProps<Props> = async () => {
  const Alumni = await getAlumni();
  return {
    props: {
      Alumni,
    },
  };
};

export default AlumniOverview;
