import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Footer from "../../components/Footer";
import Heading, { Headings } from "../../components/Heading";
import SummaryTable from "../../components/SummaryTable";
import DataFrame from "../../lib/DataFrame/DataFrame";
import getAlumni from "../../lib/data/getAlumni";
import styles from "../../styles/home.module.css";
import { Alumni } from "../../types/Alumni";

import React, { useState } from "react";
import { AgGridColumn, AgGridReact } from "ag-grid-react"; // the AG Grid React Component

import "ag-grid-community/styles/ag-grid.css"; // Core grid CSS, always needed
import "ag-grid-community/styles/ag-theme-material.css"; // Optional theme CSS

type Props = {
  alumni: Alumni[];
};

const AlumniOverview: NextPage<Props> = ({ alumni }) => {
  const AlumniDf = new DataFrame(alumni);

  const defaultColDef = {
    filter: true,
    sortable: true,
  };

  return (
    <>
      <Head>
        <title>ITC's Alumni</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Heading Tag={Headings.H1}>ITC's Alumni</Heading>

        <p className={styles.description}>Insights into ITC's Alumni.</p>
        <SummaryTable data={AlumniDf} />

        <h2>Data Table</h2>
        <div className="ag-theme-material" style={{ width: 1280, height: 500 }}>
          <AgGridReact
            rowData={alumni} // Row Data for Rows
            // columnDefs={columnDefs} // Column Defs for Columns
            defaultColDef={defaultColDef} // Default Column Properties
            pagination={true}
            paginationAutoPageSize={true}
          >
            <AgGridColumn field="contactNo" />
            <AgGridColumn
              field="examYear2"
              headerName="Exam Year"
              filter="agDateColumnFilter"
            />
            <AgGridColumn field="city" />
            <AgGridColumn field="populatedPlaceNE" />
            <AgGridColumn field="country" />
            <AgGridColumn field="countryISO3" />
            <AgGridColumn field="level" />
          </AgGridReact>
        </div>
      </main>

      <Footer />
    </>
  );
};

export const getStaticProps: GetStaticProps<Props> = async () => {
  const alumni = await getAlumni();
  return {
    props: {
      alumni,
    },
  };
};

export default AlumniOverview;
