import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Footer from "../../components/footer";
import Heading, { Headings } from "../../components/heading";
import Snapshot from "../../components/snapshot";
import getPhdCandidates from "../../lib/getPhdCandidates";
import getTestData from "../../lib/getTestData";
import styles from "../../styles/home.module.css";
import { ColumnType } from "../../types/Column";
import { PhdCandidate } from "../../types/PhdCandidate";

type Props = {
  phdCandidates: PhdCandidate[];
};

const PhdDepartments: NextPage<Props> = ({ phdCandidates }) => {
  return (
    <>
      <Head>
        <title>ITC's PhD candidates</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Heading Tag={Headings.H1}>ITC's PhD candidates</Heading>

        <Snapshot
          column={phdCandidates.map((d) => d.endDate)}
          type={ColumnType.Date}
          detailed={true}
          columnName="endDate"
        />
        <Snapshot
          column={phdCandidates.map((d) => d.startDate)}
          type={ColumnType.Date}
          detailed={true}
          columnName="startDate"
        />
        <Snapshot
          column={phdCandidates.map((d) => d.department1)}
          type={ColumnType.Ordinal}
          detailed={true}
          columnName="Department1"
        />
      </main>

      <Footer />
    </>
  );
};

export const getStaticProps: GetStaticProps<Props> = async () => {
  const phdCandidates = await getPhdCandidates();
  const test = await getTestData();
  return {
    props: {
      phdCandidates,
      test,
    },
  };
};

export default PhdDepartments;
