import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Footer from "../../components/Footer";
import Heading, { Headings } from "../../components/Heading";
import SummaryTable from "../../components/SummaryTable";
import styles from "../../styles/home.module.css";
import LinkFramed from "../../components/LinkFramed";
import * as aq from "arquero";
import useSWR from "swr";
import { useRouter } from "next/router";

const PhdOverview: NextPage = () => {
  const fetcher = (resource: RequestInfo | URL) =>
    fetch(resource).then((res) => res.json());

  const { data, error, isLoading } = useSWR(
    "/api/data/phd-candidate/",
    fetcher
  );
  const { route } = useRouter();

  return (
    <>
      <Head>
        <title>ITC&apos;s PhD candidates</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Heading Tag={Headings.H1}>ITC&apos;s PhD candidates</Heading>

        <p className={styles.description}>
          Insights into ITC&apos;s PhD candidates.
        </p>

        <div className={styles.grid}>
          <LinkFramed href={`${route}/departments`}>
            Origin Per Country and Department
          </LinkFramed>
        </div>

        {error && <div>failed to load</div>}
        {isLoading && <div>Loading …</div>}
        {!isLoading && !error && <SummaryTable data={aq.from(data)} />}
      </main>

      <Footer />
    </>
  );
};

export default PhdOverview;
