import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { MdOutlineArrowRightAlt } from "react-icons/md";
import BackToHome from "../../components/backToHome";
import Footer from "../../components/footer";
import Heading, { Headings } from "../../components/heading";
import SummaryTable from "../../components/summaryTable";
import DataFrame from "../../lib/DataFrame/DataFrame";
import getPhdCandidates from "../../lib/data/getPhdCandidates";
import styles from "../../styles/home.module.css";
import { PhdCandidate } from "../../types/PhdCandidate";

type Props = {
  phdCandidates: PhdCandidate[];
};

const PhdOverview: NextPage<Props> = ({ phdCandidates }) => {
  const phdCandidatesDf = new DataFrame(phdCandidates);
  return (
    <>
      <Head>
        <title>ITC's PhD candidates</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Heading Tag={Headings.H1}>ITC's PhD candidates</Heading>

        <p className={styles.description}>
          Insights into ITC's PhD candidates.
        </p>

        <div className={styles.grid}>
          <Link href="/phds/departments">
            <a className={styles.card}>
              <h2>
                Origin Per Country and Department <MdOutlineArrowRightAlt />
              </h2>
            </a>
          </Link>
        </div>
        <p>
          <BackToHome />
        </p>
        <SummaryTable data={phdCandidatesDf} />
      </main>

      <Footer />
    </>
  );
};

export const getStaticProps: GetStaticProps<Props> = async () => {
  const phdCandidates = await getPhdCandidates();
  return {
    props: {
      phdCandidates,
    },
  };
};

export default PhdOverview;
