import {
  useFloating,
  autoUpdate,
  useInteractions,
  useDismiss,
  useHover,
  flip,
} from "@floating-ui/react-dom-interactions";
import { offset } from "@floating-ui/dom";
import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import BackToHome from "../../components/BackToHome";
import Button from "../../components/Button";
import Footer from "../../components/Footer";
import Heading, { Headings } from "../../components/Heading";
import styles from "../../styles/home.module.css";

const UITest: NextPage = () => {
  const [open, setOpen] = useState(false);
  const { x, y, reference, floating, strategy, context } = useFloating({
    open,
    onOpenChange: setOpen,
    whileElementsMounted: autoUpdate,
    placement: "top",
    middleware: [offset(10), flip()],
  });
  const { getReferenceProps, getFloatingProps } = useInteractions([
    useDismiss(context),
    useHover(context),
  ]);

  const Placeholder = () => {
    return (
      <div
        style={{
          height: "75vh",
          width: "100%",
          background: "rgb(240,240,240)",
          borderRadius: 5,
          margin: "20px 0",
        }}
      ></div>
    );
  };

  return (
    <>
      <Head>
        <title>Floating UI Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Heading Tag={Headings.H1}>Floating UI Test</Heading>

        <Placeholder />
        <Button
          {...getReferenceProps({
            ref: reference,
          })}
        >
          Hover to show Tooltip
        </Button>
        {open && (
          <div
            {...getFloatingProps({
              ref: floating,
            })}
            style={{
              position: strategy,
              top: y ?? 0,
              left: x ?? 0,
              background: "rgb(250,250,250)",
              boxShadow: "0 0 20px rgba(0,0,0,.2)",
              padding: 5,
              borderRadius: 2,
            }}
          >
            Tooltip
          </div>
        )}

        <Placeholder />
      </main>

      <Footer />
    </>
  );
};

export default UITest;
