import type { NextPage } from "next";
import Head from "next/head";
import Footer from "../../components/Footer";
import Heading, { Headings } from "../../components/Heading";
import styles from "../../styles/home.module.css";
import { Canvas } from "@react-three/fiber";
import { OrbitControls } from "@react-three/drei";

const ThreeTest: NextPage = () => {
  return (
    <>
      <Head>
        <title>Three Line Rendering Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Heading Tag={Headings.H1}>Three Line Rendering Test</Heading>
        <Canvas
          orthographic
          camera={{ zoom: 100 }}
          style={{ width: "100%", height: "500px" }}
        >
          <axesHelper />
          <hemisphereLight
            color="#ffffff"
            groundColor="#080820"
            intensity={1.0}
          />
          <mesh>
            <boxBufferGeometry />
            <meshStandardMaterial color={"red"} />
          </mesh>
          <OrbitControls />
        </Canvas>
      </main>

      <Footer />
    </>
  );
};

export default ThreeTest;
