import { geoBertin1953 } from "d3-geo-projection";
import type { NextPage } from "next";
import Head from "next/head";
import { useContext } from "react";
import { MdTour } from "react-icons/md";
import { Step } from "react-joyride";
import { Button, Container, Heading } from "theme-ui";
import { Vector2 } from "three";
import FlightsFlowMap from "../../components/FlightsFlowMap";
import Footer from "../../components/Footer";
import Tour from "../../components/Tour";
import PointSymbol from "../../components/map/PointSymbol";
import { MapContext } from "../../components/map/layout/MapContext";
import MapLayoutFluid from "../../components/map/layout/MapLayoutFluid";
import getCountries from "../../lib/data/getCountries";
import getOdMatrix from "../../lib/data/getOdMatrix";
import type { OdMatrix } from "../../types/OdMatrix";
import { SharedPageProps } from "../../types/Props";

type Props = {
  odMatrix: OdMatrix;
} & SharedPageProps;

const Flights: NextPage<Props> = ({ odMatrix, neCountriesTopoJson }) => {
  const steps: Step[] = [
    {
      content: (
        <>
          <h3>Hub Nairobi</h3>
          <p>
            NBO, the Nairobi airport is one of the most frequently travelled
            airports by ITC staff.
          </p>
        </>
      ),
      target: "#target1",
    },
    {
      content: <div>Up in the arctic sea there are hardly any travels.</div>,
      target: "#target2",
    },
    {
      content: (
        <div>
          Southasia has always been an important area of activity for ITC.
        </div>
      ),
      target: "#target3",
    },
  ];

  return (
    <>
      <Head>
        <title>Flights</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container>
        <main>
          <Heading as="h1">ITC&apos;s travel activity</Heading>
          <MapLayoutFluid projection={geoBertin1953()}>
            <FlightsFlowMap
              odMatrix={odMatrix}
              neCountriesTopoJson={neCountriesTopoJson}
            />
            <Targets />
          </MapLayoutFluid>
          <Tour steps={steps} />
          {/* TODO: implement tour restarting */}
          <Button
            variant="muted"
            onClick={() => {
              console.log("restarting tour …");
            }}
          >
            <MdTour style={{ marginRight: 5 }} />
            Restart Tour
          </Button>
        </main>
      </Container>

      <Footer />
    </>
  );
};

export async function getStaticProps() {
  const neCountriesTopoJson = getCountries();
  const [odMatrix] = await Promise.all([getOdMatrix()]);
  return {
    props: {
      odMatrix,
      neCountriesTopoJson,
    },
  };
}

export default Flights;

const Targets = () => {
  const { width, height, projection } = useContext(MapContext);
  return (
    <g>
      <PointSymbol
        position={new Vector2(...(projection([36.9238, -1.329]) ?? [0, 0]))}
        radius={1}
        id="target1"
        fill="transparent"
        opacity={0.25}
      />
      <circle
        id="target2"
        r={1}
        fill="transparent"
        cx={width / 2}
        cy={height / 4}
      />
      <circle
        id="target3"
        r={50}
        fill="transparent"
        stroke={"black"}
        cx={width / 1.5}
        cy={height / 2}
      />
    </g>
  );
};
