import { OrbitControls } from "@react-three/drei";
import { Canvas } from "@react-three/fiber";
import * as d3 from "d3";
import type { NextPage } from "next";
import Head from "next/head";
import { Container, Heading } from "theme-ui";
import Flow3D from "../../components/map-3d/Flow3D";
import Globe from "../../components/map-3d/Globe";
import getOdMatrix from "../../lib/data/getOdMatrix";
import type { OdMatrix } from "../../types/OdMatrix";
import Footer from "../../components/Footer";

type Props = {
  odMatrix: OdMatrix;
};

const earthRadius = 1;

const Flights: NextPage<Props> = ({ odMatrix }) => {
  const flightsPerRoute = odMatrix.flows.features.map(
    (flow) => flow.properties?.value
  );
  const min = d3.min(flightsPerRoute);
  const max = d3.max(flightsPerRoute);
  const scaleWidth = d3
    .scaleLinear()
    .domain([min ?? 0, max ?? 100])
    .range([0, 100]);

  return (
    <>
      <Head>
        <title>Flights</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container>
        <main>
          <Heading as="h1">ITC&apos;s travel activity</Heading>
          <div style={{ width: "100%", height: "700px" }}>
            <Canvas camera={{ position: [0, 0, 5], fov: 30 }} shadows>
              <Globe radius={earthRadius} texture={"explorer"}>
                {odMatrix.flows.features.map((flow) => {
                  const origin = flow.geometry.coordinates[0];
                  const destination = flow.geometry.coordinates[1];
                  return (
                    <Flow3D
                      key={flow.properties.od}
                      origin={origin}
                      destination={destination}
                      value={scaleWidth(flow.properties?.value)}
                      data={flow.properties}
                    />
                  );
                })}
              </Globe>
              <OrbitControls enableZoom={false} enablePan={false} />
            </Canvas>
          </div>
        </main>
      </Container>

      <Footer />
    </>
  );
};

export async function getStaticProps() {
  const odMatrix = await getOdMatrix();
  return {
    props: {
      odMatrix,
    },
  };
}

export default Flights;
