import type { NextPage } from "next";
import Head from "next/head";
import SummaryTable from "../../components/SummaryTable";
import Footer from "../../components/Footer";
import { Container, Heading, Text, Grid } from "theme-ui";
import CardLink from "../../components/CardLink";
import * as aq from "arquero";
import useSWR from "swr";
import { useRouter } from "next/router";

const Travels: NextPage = () => {
  const { route } = useRouter();

  const links = [
    {
      href: `${route}/airports`,
      children: "Airports",
    },
    {
      href: `${route}/flights`,
      children: "Flights (map)",
    },
    {
      href: `${route}/flights3D`,
      children: "Flights (globe)",
    },
  ];

  const { data, error, isLoading } = useSWR("/api/data/flight2019/");

  return (
    <>
      <Head>
        <title>ITC&apos;s world</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <main>
          <Heading as="h1">Flights 2019</Heading>

          <Text variant="teaser">
            Insights into ITC&apos;s travels in 2019.
          </Text>

          <Grid variant="navigation">
            {links.map((l, idx) => (
              <CardLink key={idx} href={l.href}>
                <Heading as="h2">{l.children}</Heading>
              </CardLink>
            ))}
          </Grid>
          {error && <div>failed to load</div>}
          {isLoading && <div>Loading …</div>}
          {!isLoading && !error && <SummaryTable data={aq.from(data)} />}
        </main>
      </Container>

      <Footer />
    </>
  );
};

export default Travels;
