import type { NextPage } from "next";
import Head from "next/head";
import styles from "../../styles/Home.module.css";
import SummaryTable from "../../components/SummaryTable";
import Footer from "../../components/Footer";
import Heading, { Headings } from "../../components/Heading";
import LinkFramed from "../../components/LinkFramed";
import { nanoid } from "nanoid";
import * as aq from "arquero";
import useSWR from "swr";
import { useRouter } from "next/router";

const Travels: NextPage = () => {
  const { route } = useRouter();

  const links = [
    {
      href: `${route}/airports`,
      children: "Airports",
    },
    {
      href: `${route}/flights`,
      children: "Flights (map)",
    },
    {
      href: `${route}/flights3D`,
      children: "Flights (globe)",
    },
  ];

  const { data, error, isLoading } = useSWR("/api/data/flight2019/");

  return (
    <>
      <Head>
        <title>ITC&apos;s world</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Heading Tag={Headings.H1}>Flights 2019</Heading>

        <p className={styles.description}>
          Insights into ITC&apos;s travels in 2019.
        </p>

        <div className={styles.grid}>
          {links.map((l) => (
            <LinkFramed key={nanoid()} href={l.href}>
              {l.children}
            </LinkFramed>
          ))}
        </div>
        {error && <div>failed to load</div>}
        {isLoading && <div>Loading …</div>}
        {!isLoading && !error && <SummaryTable data={aq.from(data)} />}
      </main>

      <Footer />
    </>
  );
};

export default Travels;
