import * as d3 from "d3";
import { geoBertin1953 } from "d3-geo-projection";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useRef } from "react";
import styles from "../styles/Home.module.css";
import createBaseMap from "../lib/createBaseMap";

const Airports: NextPage = () => {
  useEffect(async () => {
    const flights = await fetch("/api/data/flights");
    const flightsJSON = await flights.json();

    const maxRadius = 50;
    const airports = flightsJSON.perAirport.features
      .filter((d) => d.properties.iata_code != "AMS")
      .sort((a, b) => d3.descending(a.value, b.value));

    const scale = d3
      .scaleSqrt()
      .domain(d3.extent(airports.map((d) => d.properties.value)))
      .range([0, maxRadius]);

    const worldRes = await fetch("/api/data/countries");
    const world = await worldRes.json();

    const projection = geoBertin1953();

    const svgEl = d3.select(svgRef.current);

    createBaseMap(svgEl, world, projection);

    // Airports
    const airportGroup = svgEl.append("g").attr("id", "airports");
    const airport = airportGroup.selectAll("circle").data(airports);

    airport
      .enter()
      .append("circle")
      .attr("r", (d) => scale(d.properties.value))
      .attr("cx", (d) => projection(d.geometry.coordinates)[0])
      .attr("cy", (d) => projection(d.geometry.coordinates)[1])
      .attr("stroke", "red")
      .attr("fill", "red")
      .attr("fill-opacity", 0.2)
      .attr("text", (d) => d.properties.name + ": " + d.properties.value);
  }, []);

  const svgRef = useRef(null);
  return (
    <div className={styles.container}>
      <Head>
        <title>Airports</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Airports</h1>
        <svg ref={svgRef} width={1020} height={600} />
      </main>
    </div>
  );
};

export default Airports;
