import * as d3 from "d3";
import { geoPath } from "d3-geo";
import { geoBertin1953 } from "d3-geo-projection";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useRef } from "react";
import styles from "../styles/Home.module.css";
import createBaseMap from "../lib/createBaseMap";

const Flights: NextPage = () => {
  useEffect(async () => {
    const res = await fetch("/api/data/flights");
    const json = await res.json();

    const worldRes = await fetch("/api/data/geo/countries");
    const world = await worldRes.json();

    const projection = geoBertin1953();
    const path = geoPath(projection);

    // setData(json.data)
    // setFilteredData(json.data)
    const svgEl = d3.select(svgRef.current);

    createBaseMap(svgEl, world, projection);

    // Flows
    const routes = svgEl.append("g").attr("id", "routes");
    const flow = routes.selectAll("path").data(json.odMatrix);

    flow
      .enter()
      .append("path")
      .attr("d", path)
      .attr("stroke", "black")
      .attr("fill", "none")
      .attr("stroke-width", (d) => (10 * d.properties.value) / 100)
      .attr("value", (d) => d.value)
      .attr("class", "route");
  }, []);

  // const [selectedCountry, setSelectedCountry] = useState(null)
  // const [filterData, setFilteredData] = useState(null)
  // const [data, setData] = useState(null)

  // useEffect(() => {
  //   setFilteredData(data.filter(d => d > selectedCountry))
  // }, [selectedCountry])

  const svgRef = useRef(null);
  return (
    <div className={styles.container}>
      <Head>
        <title>Flights</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1>Flights</h1>
        <svg ref={svgRef} width={1020} height={600} />
        {/* <select onChange={(e) => setSelectedCountry(e.target.value)}></select>
        <Navigation>
        <Flowmap thematicData={filteredData} geographicData="" />
        <Flowmap thematicData=" " geographicData="" /> */}
      </main>
    </div>
  );
};

export default Flights;
