import type { NextPage } from "next";
import Head from "next/head";
import SummaryTable from "../../components/SummaryTable";
import Footer from "../../components/Footer";
import { Container, Heading, Text } from "theme-ui";
import useSWR from "swr";
import * as aq from "arquero";

const Page: NextPage = () => {
  const { data, error, isLoading } = useSWR("/api/data/employment/");

  return (
    <>
      <Head>
        <title>ITC&apos;s employments</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <main>
          <Heading as="h1">Employments</Heading>
          <Text variant="teaser">Insights into ITC&apos;s employments.</Text>

          {error && <div>failed to load</div>}
          {isLoading && <div>Loading …</div>}
          {!isLoading && !error && <SummaryTable data={aq.from(data)} />}
        </main>
      </Container>

      <Footer />
    </>
  );
};

export default Page;
