import type { NextPage } from "next";
import Head from "next/head";
import Footer from "../../components/Footer";
import { Container, Heading, Text } from "theme-ui";

const Page: NextPage = () => (
  <>
    <Head>
      <title>ITC&apos;s employments</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Container>
      <main>
        <Heading as="h1">Employments</Heading>
        <Text variant="teaser">Insights into ITC&apos;s employments.</Text>
      </main>
    </Container>

    <Footer />
  </>
);

export default Page;
