import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Footer from "../../components/Footer";
import Heading, { Headings } from "../../components/Heading";
import styles from "../../styles/home.module.css";
import { feature } from "topojson-client";
import getPopulatedPlaces from "../../lib/data/getPopulatedPlaces";
import { NePopulatedPlaces } from "../../types/NeTopoJson";
import { AgGridColumn, AgGridReact } from "ag-grid-react"; // the AG Grid React Component
import "ag-grid-community/styles/ag-grid.css"; // Core grid CSS, always needed
import "ag-grid-community/styles/ag-theme-material.css"; // Optional theme CSS

type Props = {
  populatedPlacesNE: NePopulatedPlaces;
};

const PopulatedPlacesOverview: NextPage<Props> = ({ populatedPlacesNE }) => {
  const features = feature(
    populatedPlacesNE,
    populatedPlacesNE.objects.ne_populated_places
  ).features;
  const data = features.map((d) => d.properties);
  const defaultColDef = {
    sortable: true,
    filter: true,
    floatingFilter: true,
  };

  return (
    <>
      <Head>
        <title>Populated Places Natural Earth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Heading Tag={Headings.H1}>Populated Places by Natural Earth</Heading>

        <div className="ag-theme-material" style={{ width: 1280, height: 500 }}>
          <AgGridReact
            rowData={data}
            defaultColDef={defaultColDef}
            pagination={true}
            paginationAutoPageSize={true}
          >
            <AgGridColumn
              field="NAME_EN"
              headerName="Name"
              filter="agTextColumnFilter"
              suppressMenu={true}
            />
            <AgGridColumn field="ADM0_A3" headerName="ISO3" />
            <AgGridColumn field="SOV_A3" headerName="ISO3 (Sovereign State)" />
          </AgGridReact>
        </div>
      </main>

      <Footer />
    </>
  );
};

export const getStaticProps: GetStaticProps<Props> = async () => {
  const populatedPlacesNE = getPopulatedPlaces("10m");
  return {
    props: {
      populatedPlacesNE,
    },
  };
};

export default PopulatedPlacesOverview;
