import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Timeline from "../../components/charts/timeline/Timeline";
import Footer from "../../components/Footer";
import Heading, { Headings } from "../../components/Heading";
import Map from "../../components/map/layout/Map";
import SummaryTable from "../../components/SummaryTable";
import getApplicantsByCountry from "../../lib/data/getApplicantsByCountry";
import getBTORsByCountry from "../../lib/data/getBTORsByCountry";
import getPhdCandidatesByCountry from "../../lib/data/getPhdCandidatesByCountry";
import getProjectsByCountry from "../../lib/data/getProjectsByCountry";
import getTravelsByCountry from "../../lib/data/getTravelsByCountry";
import DataFrame from "../../lib/DataFrame/DataFrame";
import styles from "../../styles/home.module.css";
import { Applicant } from "../../types/Applicant";
import { PhdCandidate } from "../../types/PhdCandidate";
import { Project } from "../../types/Project";
import { TimelineEvent } from "../../types/TimelineEvent";
import { BTOR, Travel } from "../../types/Travels";

type Props = {
  applicants: Applicant[];
};

const IndonesiaApplicants: NextPage<Props> = ({ applicants }) => {
  return (
    <>
      <Head>
        <title>Origin of ITC's Applicants from Indonesia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Heading Tag={Headings.H1}>
          Origin of ITC's Applicants from Indonesia
        </Heading>
        <SummaryTable data={new DataFrame(applicants)} />
      </main>
      <Footer />
    </>
  );
};

export const getStaticProps: GetStaticProps<Props> = async () => {
  const [applicants] = await Promise.all([getApplicantsByCountry("Indonesia")]);

  return {
    props: {
      applicants,
    },
  };
};

export default IndonesiaApplicants;
