import type { NextPage } from "next";
import Head from "next/head";
import Footer from "../../components/Footer";
import Heading, { Headings } from "../../components/Heading";
import SummaryTable from "../../components/SummaryTable";
import styles from "../../styles/home.module.css";
import useSWR from "swr";
import * as aq from "arquero";

const ApplicantsOverview: NextPage = () => {
  const { data, error, isLoading } = useSWR("/api/data/application/");

  return (
    <>
      <Head>
        <title>ITC&apos;s applications</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Heading Tag={Headings.H1}>ITC&apos;s applicants</Heading>
        <p className={styles.description}>
          Insights into ITC&apos;s applications.
        </p>
        {error && <div>failed to load</div>}
        {isLoading && <div>Loading …</div>}
        {!isLoading && !error && <SummaryTable data={aq.from(data)} />}
      </main>

      <Footer />
    </>
  );
};

export default ApplicantsOverview;
