import type { NextPage } from "next";
import Head from "next/head";
import Footer from "../../components/Footer";
import Heading, { Headings } from "../../components/Heading";
import SummaryTable from "../../components/SummaryTable";
import DataFrame from "../../lib/DataFrame/DataFrame";
import styles from "../../styles/home.module.css";
import useSWR from "swr";

const ApplicantsOverview: NextPage = () => {
  const fetcher = (resource: RequestInfo | URL) =>
    fetch(resource).then((res) => res.json());

  const { data, error, isLoading } = useSWR("/api/data/application/", fetcher);

  const applicationsDf = new DataFrame(data);
  return (
    <>
      <Head>
        <title>ITC's applications</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Heading Tag={Headings.H1}>ITC's applicants</Heading>
        <p className={styles.description}>Insights into ITC's applications.</p>
        {error && <div>failed to load</div>}
        {isLoading && <div>Loading …</div>}
        {!isLoading && !error && <SummaryTable data={applicationsDf} />}
      </main>

      <Footer />
    </>
  );
};

export default ApplicantsOverview;
